### ISSUE TITLE
Cannot change quantity on purchase receipt

### ISSUE THREAD

**Issue by alconroy** [Acumatica/Acumatica-SpecialOrder-Cost-Accounting#1]
Hi,

I notice you cannot change the quanity on receipt, what do you propose if a vendor is part delivering the items, so for example if you order 10 items from the vendor and they are delivering 5 in week 1 and 5 in week 2. It seems this modification cannot cope with this which is unusal as its only targetting the cost of the item

Alan

**Comment by DhirenChhapgar** [comment]
Latest changes for 2021R2 branch allows partial receipt.
